-- Using the NYC Taxi public dataset (Yellow Trips) from Google BigQuery, complete the following exercises:
-- I decided to use the `tlc_yellow_trips_2022` table for these exercises, which contains data for taxi trips in New York City for the year 2022 because the dataset for 2023 has no rows as of the knowledge cutoff date.


-- Exercise 1: Count the number of trips in January 2022
SELECT
  COUNT(*) AS trip_count
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
WHERE
  pickup_datetime >= '2022-01-01' AND pickup_datetime < '2022-02-01';

-- trip_count
-- 2463900

-- Exercise 2: Calculate the total revenue generated by taxi trips in 2022
SELECT
  SUM(fare_amount) AS total_revenue
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
WHERE
  pickup_datetime >= '2022-01-01' AND pickup_datetime < '2022-12-31';

-- total_revenue
-- 531116603.8

-- Exercise 3: Find the most popular pickup location
SELECT 
  pickup_location_id, 
  COUNT(*) AS trip_count
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
GROUP BY
  pickup_location_id
ORDER BY
  trip_count DESC
LIMIT 1;

-- pickup_location_id	trip_count
-- 132	1743244

-- Exercise 4: Analyze the number of trips per hour of the day
SELECT 
  EXTRACT(HOUR FROM pickup_datetime) AS hour_of_day, 
  COUNT(*) AS trip_count
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
GROUP BY
  hour_of_day
ORDER BY
  hour_of_day;

-- hour_of_day	trip_count
-- 0	1001786
-- 1	661286
-- 2	440841
-- 3	291413
-- 4	200553
-- 5	231502
-- 6	567755
-- 7	1051949
-- 8	1396320
-- 9	1561361
-- 10	1719231
-- 11	1867672
-- 12	2017343
-- 13	2058545
-- 14	2205956
-- 15	2263896
-- 16	2250795
-- 17	2450718
-- 18	2575374
-- 19	2325281
-- 20	2000668
-- 21	1918459
-- 22	1768688
-- 23	1429147

-- Exercise 5: Calculate the average trip distance
SELECT
  AVG(trip_distance) AS average_trip_distance
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`;

-- average_trip_distance
-- 6.077670271

-- Exercise 6: Find the longest trip by distance
SELECT 
  pickup_datetime, 
  dropoff_datetime, 
  trip_distance
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
ORDER BY
  trip_distance DESC
LIMIT 1;

-- pickup_datetime	dropoff_datetime	trip_distance
-- 2022-10-28 05:19:00.000000 UTC	2022-10-28 05:32:00.000000 UTC	389678.46

-- Exercise 7: Calculate the total number of passengers by payment type
SELECT
  payment_type,
  SUM(passenger_count) AS total_passengers
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
GROUP BY
  payment_type;

-- payment_type	total_passengers
-- 0	
-- 5	6
-- 1	38232144
-- 4	265749
-- 2	10292210
-- 3	210382

-- Exercise 8: Find the most common drop-off location for trips paid by credit card
SELECT 
  dropoff_location_id, 
  COUNT(*) AS trip_count
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
WHERE
  payment_type = '1'
GROUP BY
  dropoff_location_id
ORDER BY
  trip_count DESC
LIMIT 1;

-- dropoff_location_id	trip_count
-- 236	1236603

-- Exercise 9: Calculate the total number of trips that had more than 4 passengers
SELECT 
  COUNT(*) AS trip_count
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
WHERE
  passenger_count > 4;

-- trip_count
-- 1062813

-- Exercise 10: Subquery - Find the average fare for trips longer than the average trip distance
SELECT
  AVG(fare_amount) AS average_fare
FROM
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
WHERE
  trip_distance > (SELECT AVG(trip_distance) FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`);

-- average_fare
-- 39.074923083